// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-es1K4nTSPcq0CGxg4JiTBnIxNChv65s',
    appId: '1:640211108399:web:e048607d954202d834fcda',
    messagingSenderId: '640211108399',
    projectId: 'unitrade-ebfdb',
    authDomain: 'unitrade-ebfdb.firebaseapp.com',
    databaseURL: 'https://unitrade-ebfdb-default-rtdb.firebaseio.com',
    storageBucket: 'unitrade-ebfdb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyQEvYRe8NQ3YC1X8FcJ_1G0WnnfuRLew',
    appId: '1:640211108399:android:09a85c31b97b3ac834fcda',
    messagingSenderId: '640211108399',
    projectId: 'unitrade-ebfdb',
    databaseURL: 'https://unitrade-ebfdb-default-rtdb.firebaseio.com',
    storageBucket: 'unitrade-ebfdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpdKJ4E7nracUnvhfU44gvRv9SvgcyjIk',
    appId: '1:640211108399:ios:b1dc5b56978ca2be34fcda',
    messagingSenderId: '640211108399',
    projectId: 'unitrade-ebfdb',
    databaseURL: 'https://unitrade-ebfdb-default-rtdb.firebaseio.com',
    storageBucket: 'unitrade-ebfdb.appspot.com',
    iosBundleId: 'com.example.unitradev1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpdKJ4E7nracUnvhfU44gvRv9SvgcyjIk',
    appId: '1:640211108399:ios:b1dc5b56978ca2be34fcda',
    messagingSenderId: '640211108399',
    projectId: 'unitrade-ebfdb',
    databaseURL: 'https://unitrade-ebfdb-default-rtdb.firebaseio.com',
    storageBucket: 'unitrade-ebfdb.appspot.com',
    iosBundleId: 'com.example.unitradev1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFCN5SWw4wqQ6hyxN0_IsiiZK1es3Y9D0',
    appId: '1:640211108399:web:87d1ff36e530bf5c34fcda',
    messagingSenderId: '640211108399',
    projectId: 'unitrade-ebfdb',
    authDomain: 'unitrade-ebfdb.firebaseapp.com',
    databaseURL: 'https://unitrade-ebfdb-default-rtdb.firebaseio.com',
    storageBucket: 'unitrade-ebfdb.appspot.com',
  );
}
